# Generated by Django 3.2.8 on 2021-10-26 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20211025_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoey',
            new_name='Category',
        ),
    ]
